# Site settings
title: Synergy Farm
description: Boarding, training, lessons
baseurl: "/pages/timothymcmackin/synergy-lens" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
phone: 555-123-4567
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# Build settings
markdown: kramdown
